import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    GroupAction,
    IncludeLaunchDescription,
)
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from moveit_configs_utils import MoveItConfigsBuilder


MOVEIT_CONFIG_PACKAGE = (
    "ur5e_mpm_d435i_rpi5_millibar_r2f85_moveit_config"
)
PLANNING_GROUP = "arm"
ROBOT_BASE_FRAME = "ur5e_base_link"


def generate_launch_description():
    use_sim_time = LaunchConfiguration("use_sim_time")
    headless = LaunchConfiguration("headless")
    launch_flexbe = LaunchConfiguration("launch_flexbe")
    launch_realsense = LaunchConfiguration("launch_realsense")
    launch_move_group = LaunchConfiguration("launch_move_group")
    pointcloud_topic = LaunchConfiguration("pointcloud_topic")
    target_frame = LaunchConfiguration("target_frame")
    gpd_config_file = LaunchConfiguration("gpd_config_file")
    gripper_offset = ParameterValue(
        LaunchConfiguration("gripper_offset"), value_type=float
    )

    # The MoveIt package's .setup_assistant file supplies the xacro mappings
    # for ur5e/mpm/d435i/rpi5/millibar/robotiq_2f85.
    moveit_config = (
        MoveItConfigsBuilder(
            "armada_robot",
            package_name=MOVEIT_CONFIG_PACKAGE,
        )
        .planning_pipelines(
            default_planning_pipeline="ompl",
            pipelines=["ompl"],
            load_all=False,
        )
        .to_moveit_configs()
    )

    robot_description = moveit_config.robot_description
    robot_description_semantic = moveit_config.robot_description_semantic
    robot_description_kinematics = moveit_config.robot_description_kinematics
    planning_pipeline_config = moveit_config.planning_pipelines
    planning_scene_monitor_parameters = moveit_config.planning_scene_monitor
    joint_limits = moveit_config.joint_limits

    trajectory_execution = {
        key: value
        for key, value in moveit_config.trajectory_execution.items()
        if key in ("moveit_manage_controllers", "trajectory_execution")
    }
    moveit_controllers = {
        key: value
        for key, value in moveit_config.trajectory_execution.items()
        if key in (
            "moveit_controller_manager",
            "moveit_simple_controller_manager",
        )
    }

    # MTC expects request_adapters as a string array, while move_group accepts
    # the value generated by MoveItConfigsBuilder.
    mtc_planning_pipeline_config = dict(planning_pipeline_config)
    if "ompl" in mtc_planning_pipeline_config:
        mtc_planning_pipeline_config["ompl"] = dict(
            mtc_planning_pipeline_config["ompl"]
        )
        request_adapters = mtc_planning_pipeline_config["ompl"].get(
            "request_adapters", []
        )
        if isinstance(request_adapters, str):
            mtc_planning_pipeline_config["ompl"]["request_adapters"] = (
                request_adapters.split()
            )

    common_move_service_parameters = [
        {"planning_group": PLANNING_GROUP},
        robot_description,
        robot_description_semantic,
        robot_description_kinematics,
        {"use_sim_time": use_sim_time},
    ]
    common_mtc_parameters = [
        {"planning_group": PLANNING_GROUP},
        robot_description,
        robot_description_semantic,
        robot_description_kinematics,
        joint_limits,
        mtc_planning_pipeline_config,
        {"use_sim_time": use_sim_time},
    ]

    run_move_group_node = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        condition=IfCondition(launch_move_group),
        output="screen",
        emulate_tty=True,
        parameters=[
            robot_description,
            robot_description_semantic,
            robot_description_kinematics,
            planning_pipeline_config,
            trajectory_execution,
            moveit_controllers,
            planning_scene_monitor_parameters,
            joint_limits,
            {"use_sim_time": use_sim_time},
            {
                "capabilities": (
                    "move_group/ExecuteTaskSolutionCapability"
                )
            },
        ],
    )

    flexbe_full = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(
                get_package_share_directory("flexbe_webui"),
                "launch",
                "flexbe_full.launch.py",
            )
        ),
        launch_arguments={"headless": headless}.items(),
        condition=IfCondition(launch_flexbe),
    )

    realsense = GroupAction(
        actions=[
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource(
                    os.path.join(
                        get_package_share_directory("armada_bringup"),
                        "launch",
                        "modules",
                        "sensors",
                        "d435i",
                        "realsense_launch.launch.py",
                    )
                ),
                launch_arguments={
                    "parent_frame": "d435i_link",
                    "child_frame": "camera_link",
                }.items(),
            )
        ],
        scoped=True,
        forwarding=False,
        condition=IfCondition(launch_realsense),
    )

    move_cartesian = Node(
        package="move_group_ros2",
        executable="cartesian_move_to_pose_service",
        name="cartesian_move_to_pose_service",
        output="screen",
        parameters=common_move_service_parameters,
    )
    move_pose = Node(
        package="move_group_ros2",
        executable="move_to_pose_service",
        name="move_to_pose_service",
        output="screen",
        parameters=common_move_service_parameters,
    )
    move_named = Node(
        package="move_group_ros2",
        executable="move_to_named_pose_service",
        name="move_to_named_pose_service",
        output="screen",
        parameters=common_move_service_parameters,
    )

    mtc_plan_and_execute_pick = Node(
        package="mtc_ros2",
        executable="mtc_plan_and_execute_pick_action",
        name="mtc_plan_and_execute_pick_action",
        output="screen",
        parameters=common_mtc_parameters,
    )
    mtc_approach_and_pick = Node(
        package="mtc_ros2",
        executable="mtc_approach_and_pick_action",
        name="mtc_approach_and_pick_action",
        output="screen",
        parameters=common_mtc_parameters,
    )
    mtc_retreat_and_place = Node(
        package="mtc_ros2",
        executable="mtc_retreat_and_place_action",
        name="mtc_retreat_and_place_action",
        output="screen",
        parameters=common_mtc_parameters,
    )

    compute_grasp_poses = Node(
        package="gpd_ros",
        executable="grasp_pose_server",
        name="grasp_pose_server",
        output="screen",
        parameters=[
            {"gripper_offset": gripper_offset},
            {"approach_dist": 0.10},
            {"retreat_dist": 0.0},
            {"grasp_rot_x": 0.0},
            {"grasp_rot_y": 0.0},
            {"grasp_rot_z": 0.0},
            {"grasp_rot_w": 1.0},
            {"target_frame": target_frame},
            {"source_frame": target_frame},
            {"use_sim_time": use_sim_time},
        ],
    )

    visualize_executed_grasp = Node(
        package="gpd_ros",
        executable="visualize_executed_grasp_server",
        name="visualize_executed_grasp_server",
        output="screen",
        parameters=[
            {"source_frame": target_frame},
            {"use_sim_time": use_sim_time},
        ],
    )

    pointcloud_parameters = [
        {"default_camera_topic": pointcloud_topic},
        {"target_frame": target_frame},
        {"timeout_sec": 3.0},
        {"use_sim_time": use_sim_time},
    ]
    get_pointcloud_service = Node(
        package="pcl_ros2",
        executable="get_point_cloud_service",
        name="get_point_cloud_service",
        output="screen",
        parameters=pointcloud_parameters,
    )
    euclidean_clustering_service = Node(
        package="pcl_ros2",
        executable="euclidean_clustering_service",
        name="euclidean_clustering_service",
        output="screen",
        parameters=pointcloud_parameters,
    )
    filter_by_indices_service = Node(
        package="pcl_ros2",
        executable="filter_by_indices_service",
        name="filter_by_indices_service",
        output="screen",
        parameters=pointcloud_parameters,
    )
    plane_segmentation_service = Node(
        package="pcl_ros2",
        executable="plane_segmentation_service",
        name="plane_segmentation_service",
        output="screen",
        parameters=[{"use_sim_time": use_sim_time}],
    )
    passthrough_filter_service = Node(
        package="pcl_ros2",
        executable="passthrough_filter_service",
        name="passthrough_filter_service",
        output="screen",
        parameters=[{"use_sim_time": use_sim_time}],
    )

    detect_grasps = Node(
        package="gpd_ros",
        executable="grasp_detection_server",
        name="grasp_detection_server",
        output="screen",
        parameters=[
            {"camera_position": [0.0, 0.0, 0.0]},
            {"config_file": gpd_config_file},
            {"grasps_topic": "clustered_grasps"},
            {"service_name": "detect_grasps"},
            {"use_sim_time": use_sim_time},
        ],
    )

    add_collision_object_service = Node(
        package="planning_scene_ros2",
        executable="add_collision_object_service",
        name="add_collision_object_service",
        output="screen",
        parameters=[
            {"frame_id": target_frame},
            {"use_sim_time": use_sim_time},
        ],
    )

    declared_arguments = [
        DeclareLaunchArgument(
            "use_sim_time",
            default_value="false",
            description="Use simulation clock instead of wall clock.",
        ),
        DeclareLaunchArgument(
            "headless",
            default_value="false",
            description="Run FlexBE without the web UI frontend.",
        ),
        DeclareLaunchArgument(
            "launch_flexbe",
            default_value="true",
            description="Start FlexBE onboard and operator control system.",
        ),
        DeclareLaunchArgument(
            "launch_realsense",
            default_value="true",
            description="Start the D435i camera and its point-cloud stream.",
        ),
        DeclareLaunchArgument(
            "launch_move_group",
            default_value="true",
            description="Start move_group (disable when another MoveIt launch owns it).",
        ),
        DeclareLaunchArgument(
            "pointcloud_topic",
            default_value="/camera/camera/depth/color/points",
            description="Point-cloud topic used by the PCL service nodes.",
        ),
        DeclareLaunchArgument(
            "target_frame",
            default_value=ROBOT_BASE_FRAME,
            description="Robot frame used for point clouds and grasp poses.",
        ),
        DeclareLaunchArgument(
            "gpd_config_file",
            default_value=os.path.join(
                os.path.expanduser("~"),
                "flexbe_ws",
                "gpd",
                "cfg",
                "ros_eigen_params.cfg",
            ),
            description="GPD detector configuration file.",
        ),
        DeclareLaunchArgument(
            "gripper_offset",
            default_value="0.041",
            description="Offset applied when converting grasps to tool poses.",
        ),
    ]

    nodes_and_includes = [
        flexbe_full,
        realsense,
        run_move_group_node,
        move_cartesian,
        move_named,
        move_pose,
        mtc_plan_and_execute_pick,
        mtc_approach_and_pick,
        mtc_retreat_and_place,
        get_pointcloud_service,
        plane_segmentation_service,
        euclidean_clustering_service,
        filter_by_indices_service,
        passthrough_filter_service,
        detect_grasps,
        compute_grasp_poses,
        visualize_executed_grasp,
        add_collision_object_service,
    ]

    return LaunchDescription(declared_arguments + nodes_and_includes)
